apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-alert-rules
  namespace: default
data:
  alert-rules.yml: |
    groups:
      - name: self-healing-platform-alerts
        rules:
          - alert: ServiceDown
            expr: up{job=~"payment-service|search-service|order-service|user-service|product-service"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service down: {{ $labels.job }}"
              description: "{{ $labels.job }} has been unreachable for more than 1 minute."

          - alert: HighKafkaProcessingErrors
            expr: rate(kafka_processing_errors_total[2m]) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Kafka processing errors in {{ $labels.job }}"
              description: "{{ $labels.job }} is producing Kafka processing errors."

          - alert: DLQMessagesDetected
            expr: increase(kafka_dlq_messages_total[5m]) > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "DLQ activity detected in {{ $labels.job }}"
              description: "{{ $labels.job }} pushed messages to DLQ in the last 5 minutes."

          - alert: NoMessagesConsumed
            expr: increase(kafka_messages_consumed_total[5m]) == 0
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "No Kafka messages consumed by {{ $labels.job }}"
              description: "{{ $labels.job }} has not consumed any Kafka messages in the last 5 minutes."

          - alert: HighKafkaProcessingLatency
            expr: (
              rate(kafka_processing_duration_seconds_sum[5m])
              /
              rate(kafka_processing_duration_seconds_count[5m])
            ) > 2
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High Kafka processing latency in {{ $labels.job }}"
              description: "{{ $labels.job }} average Kafka processing latency is above 2 seconds."