replicaCount: 1

image:
  repository: self-healing-cloud-platform-product-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 3005

env:
  PORT: "3005"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "admin"
  DB_NAME: "productdb"