version: 0.2

env:
  variables:
    REGION: ap-south-1
    REPO_NAME: order-service

phases:
  pre_build:
    commands:
      - echo "Starting PRE_BUILD..."

      # Get AWS account ID (reliable method)
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      # Debug (IMPORTANT)
      - echo "ACCOUNT_ID=$ACCOUNT_ID"
      - echo "REGION=$REGION"

      # Build ECR registry (ROOT ONLY - NO repo here)
      - REGISTRY="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"
      - echo "REGISTRY=$REGISTRY"

      # Login to ECR (THIS IS THE CORRECT FORM)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY

      - echo "ECR login completed"

  build:
    commands:
      - echo "Build phase started..."

      # Build Docker image
      - docker build -t $REPO_NAME ./services/order-service

      # Tag image for ECR
      - docker tag $REPO_NAME:latest $REGISTRY/$REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."

      # Push to ECR
      - docker push $REGISTRY/$REPO_NAME:latest

      - echo "Build completed successfully!"