version: 0.2

env:
  variables:
    REGION: ap-south-1
    REPO_NAME: order-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...

      # Get AWS Account ID safely
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      # Build full ECR URI
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME

      # Login to ECR
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

      - echo "ECR URI = $ECR_URI"

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...

      # IMPORTANT: adjust path if needed
      - docker build -t $REPO_NAME ./services/order-service

      - docker tag $REPO_NAME:latest $ECR_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...

      - docker push $ECR_URI:latest

      - echo Build and push completed successfully!