version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: userdb
      JWT_SECRET: my_super_secret_key@$$*&^%@
    depends_on:
      - postgres

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: orderdb
      JWT_SECRET: my_super_secret_key@$$*&^%@
    depends_on:
      - postgres

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: paymentdb
      JWT_SECRET: my_super_secret_key@$$*&^%@
    depends_on:
      - postgres

  search-service:
    build: ./services/search-service
    container_name: search-service
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: productsdb
    depends_on:
      - postgres

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: productsdb
      JWT_SECRET: my_super_secret_key@$$*&^%@
    depends_on:
      - postgres

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3006:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=3000
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - user-service
  #     - order-service
  #     - payment-service
  #     - product-service
  #     - search-service