apiVersion: v1
data:
  alertmanager.yml: |
    global:
      slack_api_url: xxxxxxxxx
    receivers:
    - name: default-receiver
    - name: healer-webhook
      webhook_configs:
      - send_resolved: false
        url: http://healer-service.default.svc.cluster.local:3000/heal
    - name: slack-notifications
      slack_configs:
      - channel: '#all-self-healing-cloud-platform'
        send_resolved: true
        text: '{{ range .Alerts }} *Alert:* {{ .Annotations.summary }} *Description:*
          {{ .Annotations.description }} *Namespace:* {{ .Labels.namespace }} *Deployment:*
          {{ .Labels.deployment }} *Severity:* {{ .Labels.severity }} {{ end }}'
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
    route:
      group_interval: 30s
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 1h
      routes:
      - continue: true
        matchers:
        - alertname="ServiceDown"
        receiver: healer-webhook
      - matchers:
        - namespace="prod"
        receiver: slack-notifications
    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-04-24T07:03:32Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.32.0
    helm.sh/chart: alertmanager-1.35.0
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "2819292"
  uid: 4c09c88a-91b1-46e6-9a0f-7dcff0e1099b
