kraft:
  enabled: false

replicaCount: 1

persistence:
  enabled: false

zookeeper:
  enabled: true
  persistence:
    enabled: false

listeners:
  client:
    protocol: PLAINTEXT

advertisedListeners:
  client: PLAINTEXT://kafka:9092