version: 0.2

env:
  variables:
    REGION: ap-south-1
    REPO_NAME: user-service

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."

      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGISTRY="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"

      - echo "ACCOUNT_ID=$ACCOUNT_ID"
      - echo "REGISTRY=$REGISTRY"

      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY

  build:
    commands:
      - echo "Building user-service image..."

      - docker build -t $REPO_NAME ./services/user-service
      - docker tag $REPO_NAME:latest $REGISTRY/$REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing to ECR..."

      - docker push $REGISTRY/$REPO_NAME:latest

      - echo "user-service build complete"