const MAX_ACTIVE_CHAOS_SCENARIOS = Number.parseInt(
  process.env.CHAOS_MAX_ACTIVE_SCENARIOS || "3",
  10,
);

const DEFAULT_MIN_DURATION_SECONDS = Number.parseInt(
  process.env.CHAOS_DEFAULT_MIN_DURATION_SECONDS || "60",
  10,
);

const DEFAULT_MAX_DURATION_SECONDS = Number.parseInt(
  process.env.CHAOS_DEFAULT_MAX_DURATION_SECONDS || "900",
  10,
);

const CHAOS_SCENARIOS = Object.freeze([
  {
    id: "ScaleToZero",
    category: "Availability Failures",
    name: "Scale To Zero",
    purpose: "Scale one allowlisted service deployment to 0 replicas.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: true,
    executionType: "scale_replicas",
    targetReplicas: 0,
  },
  {
    id: "CrashLoopSimulation",
    category: "Availability Failures",
    name: "Crash Loop Simulation",
    purpose: "Force repeated restarts for one allowlisted service.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ImagePullFailSimulation",
    category: "Availability Failures",
    name: "Image Pull Fail Simulation",
    purpose: "Simulate rollout failure using an invalid image reference.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: true,
    executionType: "patch_container_image",
    chaosImageTagSuffix: "chaos-invalid",
  },
  {
    id: "StuckRolloutSimulation",
    category: "Availability Failures",
    name: "Stuck Rollout Simulation",
    purpose: "Simulate rollout where new pods do not become ready.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "BadReadinessProbe",
    category: "Health Probe Failures",
    name: "Bad Readiness Probe",
    purpose: "Simulate invalid readiness checks for one service.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: true,
    executionType: "patch_readiness_probe",
    chaosReadinessPath: "/__chaos__/not-ready",
    chaosReadinessPort: 65535,
  },
  {
    id: "BadLivenessProbe",
    category: "Health Probe Failures",
    name: "Bad Liveness Probe",
    purpose: "Simulate invalid liveness checks causing restarts.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ProbeTimeoutSpike",
    category: "Health Probe Failures",
    name: "Probe Timeout Spike",
    purpose: "Simulate slow probe responses and startup delays.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "CPUStress",
    category: "Performance Degradation",
    name: "CPU Stress",
    purpose: "Simulate CPU pressure on one service.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "MemoryStress",
    category: "Performance Degradation",
    name: "Memory Stress",
    purpose: "Simulate memory pressure on one service.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "LatencyInjection",
    category: "Performance Degradation",
    name: "Latency Injection",
    purpose: "Inject fixed latency into one service path.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "SlowDependency",
    category: "Performance Degradation",
    name: "Slow Dependency",
    purpose: "Simulate slow upstream dependency responses.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ErrorRateSpike",
    category: "Error & Reliability Failures",
    name: "Error Rate Spike",
    purpose: "Simulate a controlled increase in 5xx responses.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "RetryStorm",
    category: "Error & Reliability Failures",
    name: "Retry Storm",
    purpose: "Simulate retry amplification behavior.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ThunderingHerdRecovery",
    category: "Error & Reliability Failures",
    name: "Thundering Herd Recovery",
    purpose: "Simulate surge traffic during recovery.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "CircuitBreakerOpenSimulation",
    category: "Error & Reliability Failures",
    name: "Circuit Breaker Open Simulation",
    purpose: "Simulate downstream instability causing breaker-open state.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "DatabaseUnavailable",
    category: "Dependency Failures",
    name: "Database Unavailable",
    purpose: "Simulate temporary database connectivity loss.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "KafkaUnavailable",
    category: "Dependency Failures",
    name: "Kafka Unavailable",
    purpose: "Simulate temporary Kafka broker connectivity loss.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "DNSResolutionFailure",
    category: "Dependency Failures",
    name: "DNS Resolution Failure",
    purpose: "Simulate intermittent DNS lookup failures.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ConnectionPoolExhaustion",
    category: "Dependency Failures",
    name: "Connection Pool Exhaustion",
    purpose: "Simulate exhausted dependency connection pools.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "UpstreamRateLimit",
    category: "Dependency Failures",
    name: "Upstream Rate Limit",
    purpose: "Simulate upstream throttling behavior.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ConfigRegression",
    category: "Deployment & Config Regressions",
    name: "Config Regression",
    purpose: "Apply known-bad safe config with timed auto-revert.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "SecretConfigDrift",
    category: "Deployment & Config Regressions",
    name: "Secret Config Drift",
    purpose: "Simulate inconsistent runtime configuration across pods.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "JWTMismatch",
    category: "Deployment & Config Regressions",
    name: "JWT Mismatch",
    purpose: "Simulate auth secret mismatch behavior.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "SchemaOrderMismatch",
    category: "Deployment & Config Regressions",
    name: "Schema Order Mismatch",
    purpose: "Simulate compatibility mismatch between app and dependency.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ConsumerLagSpike",
    category: "Messaging & Data Pipeline Issues",
    name: "Consumer Lag Spike",
    purpose: "Simulate Kafka consumer lag growth.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "PoisonMessageLoop",
    category: "Messaging & Data Pipeline Issues",
    name: "Poison Message Loop",
    purpose: "Simulate repeated failures on poison-message processing.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "IdempotencyFailureSimulation",
    category: "Messaging & Data Pipeline Issues",
    name: "Idempotency Failure Simulation",
    purpose: "Simulate duplicate side effects under retries.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "PodEvictionSimulation",
    category: "Infrastructure & Platform Disruptions",
    name: "Pod Eviction Simulation",
    purpose: "Simulate node or pod disruption events.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "PartialZoneImpairment",
    category: "Infrastructure & Platform Disruptions",
    name: "Partial Zone Impairment",
    purpose: "Simulate partial capacity degradation.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "EphemeralStoragePressure",
    category: "Infrastructure & Platform Disruptions",
    name: "Ephemeral Storage Pressure",
    purpose: "Simulate unstable behavior under ephemeral storage pressure.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "ScopedEgressDeny",
    category: "Infrastructure & Platform Disruptions",
    name: "Scoped Egress Deny",
    purpose: "Simulate temporary network egress denial for one dependency.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "MetricsPipelineDrop",
    category: "Observability & Control Plane Blind Spots",
    name: "Metrics Pipeline Drop",
    purpose: "Simulate missing metrics ingestion.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "LogPipelineDrop",
    category: "Observability & Control Plane Blind Spots",
    name: "Log Pipeline Drop",
    purpose: "Simulate missing log ingestion.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "AlertRouteMisconfig",
    category: "Observability & Control Plane Blind Spots",
    name: "Alert Route Misconfig",
    purpose: "Simulate alert routing misconfiguration.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
  {
    id: "HealerRateLimitConflict",
    category: "Observability & Control Plane Blind Spots",
    name: "Healer Rate Limit Conflict",
    purpose: "Simulate repeated incidents versus healer rate limits.",
    defaultDurationSeconds: 180,
    minDurationSeconds: DEFAULT_MIN_DURATION_SECONDS,
    maxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
    blastRadiusLimit: "single-service",
    autoRevert: true,
    enabled: false,
  },
]);

const getScenarioById = (scenarioId) =>
  CHAOS_SCENARIOS.find((scenario) => scenario.id === scenarioId) || null;

module.exports = {
  CHAOS_SCENARIOS,
  MAX_ACTIVE_CHAOS_SCENARIOS,
  getScenarioById,
};
