apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: 348071628290.dkr.ecr.ap-south-1.amazonaws.com/search-service:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          ports:
            - containerPort: 5003

          env:
            - name: PORT
              value: "5003"

            - name: DB_HOST
              value: "postgres.default.svc.cluster.local"

            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin
            - name: DB_NAME
              value: searchdb
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092
            - name: KAFKA_CONSUMER_GROUP
              value: "${KAFKA_CONSUMER_GROUP}"
            - name: ORDER_CREATED_TOPIC
              value: "${ORDER_CREATED_TOPIC}"
            - name: ORDER_CREATED_DLQ_TOPIC
              value: "${ORDER_CREATED_DLQ_TOPIC}"