apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 348071628290.dkr.ecr.ap-south-1.amazonaws.com/order-service:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"

            - name: DB_HOST
              value: "postgres.default.svc.cluster.local"

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              value: admin

            - name: DB_PASSWORD
              value: admin

            - name: DB_NAME
              value: orderdb

            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092

            - name: PRODUCT_SERVICE_URL
              value: http://product-service:3005

            - name: JWT_SECRET
              value: my_super_secret_key

            - name: ORDER_CREATED_TOPIC
              value: "${ORDER_CREATED_TOPIC}"

            - name: ORDER_CREATED_DLQ_TOPIC
              value: "${ORDER_CREATED_DLQ_TOPIC}"
