apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 348071628290.dkr.ecr.ap-south-1.amazonaws.com/payment-service:${IMAGE_TAG}
          imagePullPolicy: Always

          ports:
            - containerPort: 4000

          env:
            - name: PORT
              value: "4000"

            - name: DB_HOST
              value: "postgres.default.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin
            - name: DB_NAME
              value: paymentdb
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092
            - name: KAFKA_CONSUMER_GROUP
              value: "${KAFKA_CONSUMER_GROUP}"
            - name: ORDER_CREATED_TOPIC
              value: "${ORDER_CREATED_TOPIC}"
            - name: ORDER_CREATED_DLQ_TOPIC
              value: "${ORDER_CREATED_DLQ_TOPIC}"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3003"

          # ✅ HEALTH CHECKS
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10

          # ✅ STABILITY IMPROVEMENT (IMPORTANT FOR KAFKA SERVICES)
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"